apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: spoke-cluster-secret
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: spoke-cluster-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
      - target: Annotations
        literal: "{{ .metadata }}"
      - target: Labels
        literal: "{{ .addons }}"
      data:
        config: "{{ .config  }}"
        name: "{{ .name  }}"
        server: "{{ .server  }}"
        environment: "{{ .environment  }}"
  data:
    - secretKey: config
      remoteRef:
        key: hub/spoke-cluster-secret
        property: config
    - secretKey: name
      remoteRef:
        key: hub/spoke-cluster-secret
        property: cluster_name
    - secretKey: server
      remoteRef:
        key: hub/spoke-cluster-secret
        property: server
    - secretKey: environment
      remoteRef:
        key: hub/spoke-cluster-secret
        property: environment
    - secretKey: metadata
      remoteRef:
        key: hub/spoke-cluster-secret
        property: metadata
    - secretKey: addons
      remoteRef:
        key: hub/spoke-cluster-secret
        property: addons



